# 1. 添加 permissions 字段，给 GITHUB_TOKEN 分配推送权限
permissions:
  packages: write  # 关键：允许推送镜像到 GHCR
  contents: read   # 允许读取仓库代码（构建需要）

  # 2. 登录步骤改为登录 GHCR
  - name: Login to GitHub Container Registry
    uses: docker/login-action@v2
    with:
      registry: ghcr.io
      username: ${{ github.actor }}  # 自动获取当前 GitHub 用户名
      password: ${{ secrets.GITHUB_TOKEN }}  # 用内置密钥

  # 3. 构建推送步骤，镜像标签改为 GHCR 格式
  - name: Build and push
    uses: docker/build-push-action@v4
    with:
      context: .
      platforms: linux/amd64,linux/arm,linux/arm64
      push: true
      # 镜像标签：ghcr.io/你的GitHub用户名/你的镜像名:版本
      tags: ghcr.io/75412701/sun-panel-v2:${{ env.APP_VERSION }},ghcr.io/75412701/sun-panel-v2:latest
