name: docker-push

on:
  workflow_dispatch:
  # 暂时取消自动编译，优化后重新开启
  # push:
  #   tags:
  #     - 'v*'

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 步骤1：安装 Node.js 22.10.0（自带 npm）
      - name: Set up Node.js 22.10.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.10.0'
          cache: 'npm'  # 先缓存 npm（后续用 npm 装 pnpm）
          cache-dependency-path: 'package.json'  # 基于 package.json 缓存 npm 依赖

      # 步骤2：通过 npm 全局安装 pnpm（关键修复：解决 pnpm 找不到的问题）
      - name: Install pnpm globally via npm
        run: |
          npm install -g pnpm@latest  # 用 Node.js 自带的 npm 安装 pnpm
          pnpm --version  # 验证 pnpm 安装成功（可选，用于调试）

      # 步骤3：用 pnpm 安装前端依赖（此时 pnpm 已在 PATH 中）
      - name: Install frontend dependencies with pnpm
        run: |
          pnpm install --frozen-lockfile  # 基于锁定文件安装，确保依赖一致

      # 步骤4：预执行类型检查和构建（提前暴露错误）
      - name: Run type check and build frontend
        run: |
          pnpm run type-check
          pnpm run build

      # 后续步骤（版本读取、QEMU、Docker 构建）不变
      - name: Read version from file
        id: read_version
        run: echo "APP_VERSION=$(cut -d '|' -f 2 ./service/assets/version)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository owner
        id: lowercase
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            NODE_VERSION=22.10.0
          tags: |
            ghcr.io/${{ steps.lowercase.outputs.owner }}/sun-panel-v2:${{ env.APP_VERSION }}
            ghcr.io/${{ steps.lowercase.outputs.owner }}/sun-panel-v2:latest
