name: docker-push

on:
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 验证 npm 锁定文件存在（npm 生成的是 package-lock.json）
      - name: Verify package-lock.json exists
        run: |
          if [ -f "package-lock.json" ]; then
            echo "package-lock.json found. File size: $(du -h package-lock.json)"
          else
            echo "ERROR: package-lock.json not found (npm 锁定文件缺失)"
            exit 1
          fi

      # 设置与本地一致的 Node.js 22.10.0（自带 npm 10.9.0）
      - name: Set up Node.js 22.10.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.10.0'
          cache: 'npm'  # 缓存 npm 依赖
          cache-dependency-path: 'package-lock.json'  # 基于 npm 锁定文件缓存

      # 使用 npm 安装依赖（与本地一致）
      - name: Install dependencies with npm
        run: npm ci  # 等同于 npm install --frozen-lockfile，严格遵循锁定文件

      # 执行类型检查和构建（使用 npm 运行脚本）
      - name: Run type check and build
        run: |
          npm run type-check
          npm run build

      # 读取版本信息（保持不变）
      - name: Read version from file
        id: read_version
        run: echo "APP_VERSION=$(cut -d '|' -f 2 ./service/assets/version)" >> $GITHUB_ENV

      # Docker 构建相关步骤（保持不变）
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository owner
        id: lowercase
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            NODE_VERSION=22.10.0
          tags: |
            ghcr.io/${{ steps.lowercase.outputs.owner }}/sun-panel-v2:${{ env.APP_VERSION }}
            ghcr.io/${{ steps.lowercase.outputs.owner }}/sun-panel-v2:latest
